version: "2"

services:
  db:
    image: "bitnami/postgresql:latest"
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    networks:
      - pg_network
    environment:
      - "POSTGRESQL_USERNAME=postgres"
      - "POSTGRESQL_PASSWORD=postgres"
      - "POSTGRESQL_DATABASE=postgres"

networks:
  pg_network:
    driver: bridge

volumes:
  postgresql_data:
    driver: local
