version: "2"

services:
  postgresql:
    image: "bitnami/postgresql:latest"
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    environment:
      - "POSTGRESQL_USERNAME=postgres"
      - "POSTGRESQL_PASSWORD=postgres"
      - "POSTGRESQL_DATABASE=postgres"

volumes:
  postgresql_data:
    driver: local
