version: "3"
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    privileged: true
    ports:
      - "3003:3000"
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
    volumes:
      - storage:/var/lib/grafana
volumes:
  storage: