services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3003:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=hafiyyanabdulaziz
      - GF_SECURITY_ADMIN_PASSWORD=MICROSOFTsaya1!
      # Mengaktifkan fitur Embed HTML dan Script di Text Panel
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      # Opsional: Jika ingin grafana bisa dimasukkan ke iframe lain
      - GF_SECURITY_ALLOW_EMBEDDING=true
    user: "472"
    restart: unless-stopped
