version: "3.8"

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      # Format: ./nama-folder-lokal:/jalur/di/dalam/kontainer
      - ./influxdb2_data:/var/lib/influxdb2
      - ./influxdb2_config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=hafiyyanabdulaziz
      - DOCKER_INFLUXDB_INIT_PASSWORD=MICROSOFTsaya1!
      - DOCKER_INFLUXDB_INIT_ORG=hafiyyanabdulaziz-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-token
    restart: unless-stopped
